### ISSUE TITLE
ERROR:homeassistant.scripts.check_config:BURB

### ISSUE THREAD

**Issue by Spirituss** [custom-components/sensor.rpi_power#27]
After the last component update it doesn't work with Home Assistant. I have the following error in HA log:

```ERROR:homeassistant.scripts.check_config:BURB
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/scripts/check_config.py", line 209, in check
    check_ha_config_file(hass))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/scripts/check_config.py", line 403, in check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 139, in get_platform
    "{}.{}".format(self.pkg_path, platform_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/rpi_power/sensor.py", line 45
    self._description = 'Everything is working as intended'
    ^
IndentationError: unexpected indent
Fatal error while loading config: unexpected indent (sensor.py, line 45)
Failed config
  General Errors: 
    - unexpected indent (sensor.py, line 45)```

**Comment by swetoast** [comment]
fixed
